# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mSSL_dpe <- function(X, Y, lambdas = list(lambda1 = 1, lambda0 = seq(10, nrow(X), length = 10)), 
                     xislambdas = list(lambda1 = 1, lambda0 = seq(10, nrow(X), length = 10)),
                     xis = list(xi1 = 0.01 * nrow(X), xi0 = seq(0.1 * nrow(X), nrow(X), length = 10)),
                     theta_hyper_params = c(1, ncol(X) * ncol(Y)),
                     eta_hyper_params = c(1, ncol(Y)),
                     diag_penalty = 1,
                     max_iter = 500,
                     eps = 1e-3,
                     s_max_condition = 10*nrow(X),
                     obj_counter_max = 5,
                     verbose = 0) {
    .Call('_mSSL_mSSL_dpe', PACKAGE = 'mSSL', X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, s_max_condition, obj_counter_max, verbose)
}

mSSL_dcpe <- function(X, Y, lambdas = list(lambda1 = 1, lambda0 = seq(10, nrow(X), length = 10)),
                      xis = list(xi1 = 0.01 * nrow(X), xi0 = seq(0.1 * nrow(X), nrow(X), length = 10)),
                      theta_hyper_params = c(1, ncol(X) * ncol(Y)),
                      eta_hyper_params = c(1, ncol(Y)),
                      diag_penalty = 1,
                      max_iter = 500,
                      eps = 1e-3,
                      verbose = 5) {
    .Call('_mSSL_mSSL_dcpe', PACKAGE = 'mSSL', X, Y, lambdas, xis, theta_hyper_params, eta_hyper_params, diag_penalty, max_iter, eps, verbose)
}

gSSL <- function(Y, xis = list(xi1 = 0.01 * nrow(Y), xi0 = seq(0.01 * nrow(Y), nrow(Y), length = 10)),
                 eta_hyper_params = c(1, ncol(Y)),
                 diag_penalty = 1,
                 max_iter = 500,
                 eps = 1-e3,
                 obj_counter_max = 5,
                 verbose = 0) {
    .Call('_mSSL_gSSL', PACKAGE = 'mSSL', Y, xis, eta_hyper_params, diag_penalty, max_iter, eps, obj_counter_max, verbose)
}

